<?php
// config/enemies.php — Database nemici per combattimento
$enemies = [
    [
        'nome' => 'Francesco Orciuoli',
        'lvl' => 3,
        'attacco' => 25,
        'vita' => 100,
        'difesa' => 10,
        'velocità' => 8,
        'xp_drop' => 30,
        'ff_drop_min' => 3,
        'ff_drop_max' => 8,
        'img' => 'Marco e Stepan.png', // placeholder
    ],
    [
        'nome' => 'Matteo Iazzetta',
        'lvl' => 5,
        'attacco' => 35,
        'vita' => 150,
        'difesa' => 15,
        'velocità' => 12,
        'xp_drop' => 50,
        'ff_drop_min' => 5,
        'ff_drop_max' => 12,
        'img' => 'Michele e Bruno.png', // placeholder
    ],
    [
        'nome' => 'Cesarini Shadow',
        'lvl' => 8,
        'attacco' => 50,
        'vita' => 250,
        'difesa' => 20,
        'velocità' => 14,
        'xp_drop' => 90,
        'ff_drop_min' => 8,
        'ff_drop_max' => 18,
        'img' => 'Michele e Cesarini.png',
    ],
    [
        'nome' => 'Bruno il Pinguino',
        'lvl' => 10,
        'attacco' => 45,
        'vita' => 350,
        'difesa' => 30,
        'velocità' => 5,
        'xp_drop' => 130,
        'ff_drop_min' => 10,
        'ff_drop_max' => 22,
        'img' => 'Bruno Silvati.png',
    ],
    [
        'nome' => 'Stepan il Guerriero',
        'lvl' => 12,
        'attacco' => 60,
        'vita' => 400,
        'difesa' => 25,
        'velocità' => 18,
        'xp_drop' => 170,
        'ff_drop_min' => 12,
        'ff_drop_max' => 28,
        'img' => 'Stepan Maksyimiv.png',
    ],
    [
        'nome' => 'Umberto il Dio',
        'lvl' => 15,
        'attacco' => 75,
        'vita' => 550,
        'difesa' => 35,
        'velocità' => 20,
        'xp_drop' => 250,
        'ff_drop_min' => 18,
        'ff_drop_max' => 35,
        'img' => 'Umberto Cesarini.png',
    ],
];
