<?php
// config/enemies.php — Database nemici per combattimento
// Stats bilanciate: HP e danni proporzionali alle carte comuni
$enemies = [
    [
        'nome' => 'Francesco Orciuoli',
        'lvl' => 3,
        'attacco' => 15,
        'vita' => 60,
        'difesa' => 5,
        'velocita' => 10,
        'xp_drop' => 20,
        'ff_drop_min' => 5,
        'ff_drop_max' => 12,
        'img' => 'Marco e Stepan.png',
    ],
    [
        'nome' => 'Matteo Iazzetta',
        'lvl' => 5,
        'attacco' => 22,
        'vita' => 90,
        'difesa' => 8,
        'velocita' => 14,
        'xp_drop' => 35,
        'ff_drop_min' => 8,
        'ff_drop_max' => 16,
        'img' => 'Michele e Bruno.png',
    ],
    [
        'nome' => 'Cesarini Shadow',
        'lvl' => 8,
        'attacco' => 30,
        'vita' => 140,
        'difesa' => 12,
        'velocita' => 16,
        'xp_drop' => 55,
        'ff_drop_min' => 12,
        'ff_drop_max' => 22,
        'img' => 'Michele e Cesarini.png',
    ],
    [
        'nome' => 'Bruno il Pinguino',
        'lvl' => 10,
        'attacco' => 35,
        'vita' => 200,
        'difesa' => 18,
        'velocita' => 8,
        'xp_drop' => 80,
        'ff_drop_min' => 15,
        'ff_drop_max' => 28,
        'img' => 'Bruno Silvati.png',
    ],
    [
        'nome' => 'Stepan il Guerriero',
        'lvl' => 12,
        'attacco' => 45,
        'vita' => 280,
        'difesa' => 20,
        'velocita' => 22,
        'xp_drop' => 110,
        'ff_drop_min' => 18,
        'ff_drop_max' => 35,
        'img' => 'Stepan Maksyimiv.png',
    ],
    [
        'nome' => 'Umberto il Dio',
        'lvl' => 15,
        'attacco' => 55,
        'vita' => 400,
        'difesa' => 30,
        'velocita' => 25,
        'xp_drop' => 160,
        'ff_drop_min' => 25,
        'ff_drop_max' => 45,
        'img' => 'Umberto Cesarini.png',
    ],
];
