<?php
// config/enemies.php — Database nemici per combattimento
// Ogni nemico: nome, livello, stats-base (attacco, vita, difesa, velocità), immagine opzionale, xp_drop

$enemies = [
    [
        'nome' => 'Francesco Orciuoli',
        'lvl' => 3,
        'attacco' => 25,
        'vita' => 120,
        'difesa' => 10,
        'velocità' => 8,
        'xp_drop' => 45,
        'ff_drop_min' => 2,
        'ff_drop_max' => 5,
        'img' => 'Antonio e Bruno.png',
        'rarity' => 'raro',
    ],
    [
        'nome' => 'Matteo Iazzetta',
        'lvl' => 5,
        'attacco' => 35,
        'vita' => 180,
        'difesa' => 15,
        'velocità' => 12,
        'xp_drop' => 75,
        'ff_drop_min' => 4,
        'ff_drop_max' => 8,
        'img' => 'Michele e Bruno.png',
        'rarity' => 'epico',
    ],
    [
        'nome' => 'Cesarini Shadow',
        'lvl' => 8,
        'attacco' => 50,
        'vita' => 280,
        'difesa' => 20,
        'velocità' => 14,
        'xp_drop' => 120,
        'ff_drop_min' => 6,
        'ff_drop_max' => 12,
        'img' => 'Michele e Cesarini.png',
        'rarity' => 'mitico',
    ],
    [
        'nome' => 'Bruno il Pinguino',
        'lvl' => 10,
        'attacco' => 45,
        'vita' => 400,
        'difesa' => 30,
        'velocità' => 5,
        'xp_drop' => 180,
        'ff_drop_min' => 8,
        'ff_drop_max' => 15,
        'img' => 'Bruno Silvati.png',
        'rarity' => 'leggendario',
    ],
    [
        'nome' => 'Stepan il Guerriero',
        'lvl' => 12,
        'attacco' => 65,
        'vita' => 350,
        'difesa' => 25,
        'velocità' => 18,
        'xp_drop' => 220,
        'ff_drop_min' => 10,
        'ff_drop_max' => 20,
        'img' => 'Stepan Maksyimiv.png',
        'rarity' => 'mitico',
    ],
    [
        'nome' => 'Umberto il Dio',
        'lvl' => 15,
        'attacco' => 80,
        'vita' => 500,
        'difesa' => 35,
        'velocità' => 20,
        'xp_drop' => 350,
        'ff_drop_min' => 15,
        'ff_drop_max' => 30,
        'img' => 'Umberto Cesarini.png',
        'rarity' => 'segreto',
    ],
];
